export const SUPPORTED_LANGUAGES = [
  { code: 'ru', label: 'Русский' },
  { code: 'en', label: 'English' },
  { code: 'tr', label: 'Türkçe' }
];

const translations = {
  ru: {
    menu_title: 'Пиратский\nМорской Бой',
    menu_subtitle: 'КАМПАНИЯ СОКРОВИЩ',
    play: 'Играть',
    campaign: 'Кампания',
    quick_battle: 'Быстрый бой',
    arsenal: 'Арсенал',
    settings: 'Настройки',
    close: 'Закрыть',
    back: 'Назад',
    shop: 'Магазин',
    career: 'КАРЬЕРА',
    rank: 'Ранг',
    gold: 'Золото',
    xp: 'Опыт',
    admiral_chest: 'Сундук адмирала',
    open_for_ad: 'Открыть за рекламу',
    available_tomorrow: 'Доступно завтра',
    open: 'Открыть',
    tomorrow: 'Завтра',
    language: 'Язык',
    sfx: 'Звук эффектов',
    music: 'Музыка',
    music_volume: 'Громкость музыки',
    sfx_volume: 'Громкость эффектов',
    on: 'Вкл',
    off: 'Выкл',
    fleet_preparation: 'Подготовка флота',
    preparation_timer: 'Подготовка',
    ships: 'КОРАБЛИ',
    ships_hint: 'Выберите корабль и укажите клетку на поле.',
    commands: 'КОМАНДЫ',
    rotate_horizontal: 'Поворот: горизонт.',
    rotate_vertical: 'Поворот: вертик.',
    auto_place: 'Авторасстановка',
    ready_to_battle: 'Готов к бою',
    cannot_place: 'Нельзя поставить сюда',
    fleet_ready: 'Флот расставлен',
    your_fleet: 'Ваш флот',
    enemy_waters: 'Вражеские воды',
    logbook: 'Бортовой журнал',
    your_turn: 'Ваш ход',
    opponent_turn: 'Ход соперника',
    radar: 'Радар',
    barrage: 'Залп',
    torpedo: 'Торпеда',
    cancel: 'Отмена',
    row: 'Строка',
    column: 'Колонка',
    menu: 'Меню',
    leave_battle: 'Покинуть бой?',
    leave_battle_text: 'Текущий бой будет завершён без награды.',
    stay: 'Остаться',
    to_menu: 'В меню',
    victory: 'Победа!',
    defeat: 'Поражение',
    captain_chest_opened: 'Сундук капитана открыт',
    crew_saved_loot: 'Команда спасла часть добычи',
    to_campaign: 'В кампанию',
    play_again: 'Играть снова',
    double_reward: 'Удвоить за рекламу',
    reward_received: 'Награда получена',
    career_xp: 'Опыт карьеры',
    rank_up_title: 'Поздравляем!',
    rank_up_text: 'Вам присвоен новый ранг:',
    rank_reward: 'Премия за ранг',
    continue: 'Продолжить',
    shop_title: 'Пиратская лавка',
    buy: 'Купить',
    selected: 'Выбрано',
    select: 'Выбрать',
    not_enough_gold: 'Не хватает золота',
    skin_selected: 'Скин выбран',
    purchase_ready: 'Покупка готова',
    hit: 'Попадание!',
    miss: 'Промах!',
    opponent_hit: 'Соперник попал!',
    opponent_miss: 'Соперник промахнулся.',
    victory_log: 'Победа! Сундук ждёт капитана.',
    defeat_log: 'Флот разбит. Команда отступает.',
    daily_already_opened: 'Сундук уже открыт. Новый будет завтра.'
  },
  en: {
    menu_title: 'Pirate\nSea Battle',
    menu_subtitle: 'TREASURE CAMPAIGN',
    play: 'Play',
    campaign: 'Campaign',
    quick_battle: 'Quick Battle',
    arsenal: 'Arsenal',
    settings: 'Settings',
    close: 'Close',
    back: 'Back',
    shop: 'Shop',
    career: 'CAREER',
    rank: 'Rank',
    gold: 'Gold',
    xp: 'XP',
    admiral_chest: 'Admiral Chest',
    open_for_ad: 'Open with ad',
    available_tomorrow: 'Available tomorrow',
    open: 'Open',
    tomorrow: 'Tomorrow',
    language: 'Language',
    sfx: 'Effects sound',
    music: 'Music',
    music_volume: 'Music volume',
    sfx_volume: 'Effects volume',
    on: 'On',
    off: 'Off',
    fleet_preparation: 'Fleet Preparation',
    preparation_timer: 'Preparation',
    ships: 'SHIPS',
    ships_hint: 'Choose a ship and place it on the grid.',
    commands: 'COMMANDS',
    rotate_horizontal: 'Rotate: horizontal',
    rotate_vertical: 'Rotate: vertical',
    auto_place: 'Auto Place',
    ready_to_battle: 'Ready',
    cannot_place: 'Cannot place here',
    fleet_ready: 'Fleet is ready',
    your_fleet: 'Your Fleet',
    enemy_waters: 'Opponent Waters',
    logbook: 'Logbook',
    your_turn: 'Your turn',
    opponent_turn: 'Opponent turn',
    radar: 'Radar',
    barrage: 'Barrage',
    torpedo: 'Torpedo',
    cancel: 'Cancel',
    row: 'Row',
    column: 'Column',
    menu: 'Menu',
    leave_battle: 'Leave battle?',
    leave_battle_text: 'This battle will end without rewards.',
    stay: 'Stay',
    to_menu: 'To menu',
    victory: 'Victory!',
    defeat: 'Defeat',
    captain_chest_opened: 'Captain chest opened',
    crew_saved_loot: 'The crew saved part of the loot',
    to_campaign: 'To Campaign',
    play_again: 'Play again',
    double_reward: 'Double with ad',
    reward_received: 'Reward claimed',
    career_xp: 'Career XP',
    rank_up_title: 'Congratulations!',
    rank_up_text: 'You have been promoted to:',
    rank_reward: 'Rank bonus',
    continue: 'Continue',
    shop_title: 'Pirate Shop',
    buy: 'Buy',
    selected: 'Selected',
    select: 'Select',
    not_enough_gold: 'Not enough gold',
    skin_selected: 'Skin selected',
    purchase_ready: 'Purchase ready',
    hit: 'Hit!',
    miss: 'Miss!',
    opponent_hit: 'Opponent hit!',
    opponent_miss: 'Opponent missed.',
    victory_log: 'Victory! The chest awaits.',
    defeat_log: 'Fleet defeated. The crew retreats.',
    daily_already_opened: 'Chest already opened. Come back tomorrow.'
  },
  tr: {
    menu_title: 'Korsan\nDeniz Savaşı',
    menu_subtitle: 'HAZİNE SEFERİ',
    play: 'Oyna',
    campaign: 'Sefer',
    quick_battle: 'Hızlı Savaş',
    arsenal: 'Cephanelik',
    settings: 'Ayarlar',
    close: 'Kapat',
    back: 'Geri',
    shop: 'Dükkan',
    career: 'KARİYER',
    rank: 'Rütbe',
    gold: 'Altın',
    xp: 'XP',
    admiral_chest: 'Amiral Sandığı',
    open_for_ad: 'Reklamla aç',
    available_tomorrow: 'Yarın açılır',
    open: 'Aç',
    tomorrow: 'Yarın',
    language: 'Dil',
    sfx: 'Efekt sesi',
    music: 'Müzik',
    music_volume: 'Müzik sesi',
    sfx_volume: 'Efekt sesi',
    on: 'Açık',
    off: 'Kapalı',
    fleet_preparation: 'Filo Hazırlığı',
    preparation_timer: 'Hazırlık',
    ships: 'GEMİLER',
    ships_hint: 'Bir gemi seç ve tabloya yerleştir.',
    commands: 'KOMUTLAR',
    rotate_horizontal: 'Çevir: yatay',
    rotate_vertical: 'Çevir: dikey',
    auto_place: 'Otomatik Yerleştir',
    ready_to_battle: 'Savaşa Hazır',
    cannot_place: 'Buraya yerleştirilemez',
    fleet_ready: 'Filo hazır',
    your_fleet: 'Filon',
    enemy_waters: 'Rakip Suları',
    logbook: 'Seyir Defteri',
    your_turn: 'Sıra sende',
    opponent_turn: 'Rakibin sırası',
    radar: 'Radar',
    barrage: 'Yaylım',
    torpedo: 'Torpido',
    cancel: 'İptal',
    row: 'Satır',
    column: 'Sütun',
    menu: 'Menü',
    leave_battle: 'Savaştan çıkılsın mı?',
    leave_battle_text: 'Bu savaş ödülsüz bitecek.',
    stay: 'Kal',
    to_menu: 'Menüye',
    victory: 'Zafer!',
    defeat: 'Yenilgi',
    captain_chest_opened: 'Kaptan sandığı açıldı',
    crew_saved_loot: 'Mürettebat ganimetin bir kısmını kurtardı',
    to_campaign: 'Sefere',
    play_again: 'Tekrar oyna',
    double_reward: 'Reklamla ikiye katla',
    reward_received: 'Ödül alındı',
    career_xp: 'Kariyer XP',
    rank_up_title: 'Tebrikler!',
    rank_up_text: 'Yeni rütben:',
    rank_reward: 'Rütbe ödülü',
    continue: 'Devam',
    shop_title: 'Korsan Dükkanı',
    buy: 'Satın al',
    selected: 'Seçildi',
    select: 'Seç',
    not_enough_gold: 'Altın yetersiz',
    skin_selected: 'Görünüm seçildi',
    purchase_ready: 'Satın alma tamam',
    hit: 'İsabet!',
    miss: 'Iska!',
    opponent_hit: 'Rakip vurdu!',
    opponent_miss: 'Rakip ıskaladı.',
    victory_log: 'Zafer! Sandık seni bekliyor.',
    defeat_log: 'Filo yenildi. Mürettebat çekiliyor.',
    daily_already_opened: 'Sandık açıldı. Yarın tekrar gel.'
  }
};

let currentLanguage = 'ru';

export const LocalizationService = {
  init(profile) {
    currentLanguage = profile?.settings?.language ?? currentLanguage;
    return currentLanguage;
  },

  t(key, params = {}) {
    const value = translations[currentLanguage]?.[key] ?? translations.ru[key] ?? key;
    return Object.entries(params).reduce((text, [param, replacement]) => {
      return text.replaceAll(`{${param}}`, String(replacement));
    }, value);
  },

  setLanguage(lang) {
    currentLanguage = translations[lang] ? lang : 'ru';
    return currentLanguage;
  },

  getLanguage() {
    return currentLanguage;
  },

  getSupportedLanguages() {
    return SUPPORTED_LANGUAGES;
  }
};

export const t = (key, params) => LocalizationService.t(key, params);
