export const SUPPORTED_LANGUAGES = [
  { code: 'ru', label: 'Русский' },
  { code: 'en', label: 'English' },
  { code: 'tr', label: 'Türkçe' }
];

const translations = {
  ru: {
    menu_title: 'Пиратский\nМорской Бой',
    menu_title_line_1: 'Пиратский Морской Бой',
    menu_title_line_2: 'Карта Сокровищ',
    menu_subtitle: 'КАМПАНИЯ СОКРОВИЩ',
    play: 'Играть',
    campaign: 'Кампания',
    campaign_stars: 'Звёзды кампании',
    next_reward: 'Следующая награда',
    quick_battle: 'Быстрый бой',
    arsenal: 'Арсенал',
    settings: 'Настройки',
    close: 'Закрыть',
    back: 'Назад',
    shop: 'Магазин',
    career: 'КАРЬЕРА',
    rank: 'Ранг',
    gold: 'Золото',
    price_gold: '{amount} золота',
    xp: 'Опыт',
    admiral_chest: 'Сундук адмирала',
    open_for_ad: 'Открыть за рекламу',
    available_tomorrow: 'Доступно завтра',
    available: 'Доступен',
    opens_in: 'Через {time}',
    wins_until_open: 'Осталось побед: {count}',
    daily_chest_rules: '1 раз в 24 часа: золото, опыт, шанс на способность.',
    rare_chest_rules: 'Раз в 6 часов или после 3 побед: больше золота, опыта и способностей.',
    chapter: 'Глава',
    locked_chapter: 'Глава закрыта',
    opens_after_previous_chapter: 'Откроется после прохождения предыдущей главы',
    open: 'Открыть',
    tomorrow: 'Завтра',
    language: 'Язык',
    sfx: 'Звук эффектов',
    music: 'Музыка',
    music_volume: 'Громкость музыки',
    sfx_volume: 'Громкость эффектов',
    on: 'Вкл',
    off: 'Выкл',
    fleet_preparation: 'Подготовка флота',
    preparation_timer: 'Подготовка',
    ships: 'КОРАБЛИ',
    ships_hint: 'Выберите корабль и укажите клетку на поле.',
    commands: 'КОМАНДЫ',
    rotate_horizontal: 'Поворот: горизонт.',
    rotate_vertical: 'Поворот: вертик.',
    auto_place: 'Авторасстановка',
    current_ship: 'Текущий корабль',
    orientation_horizontal: 'Горизонтально',
    orientation_vertical: 'Вертикально',
    ship_deck: '{count}-палубный корабль',
    ready_to_battle: 'Готов к бою',
    cannot_place: 'Нельзя поставить сюда',
    fleet_ready: 'Флот расставлен',
    your_fleet: 'Ваш флот',
    enemy_waters: 'Вражеские воды',
    logbook: 'Бортовой журнал',
    your_turn: 'Ваш ход',
    opponent_turn: 'Ход соперника',
    radar: 'Радар',
    barrage: 'Залп',
    salvo: 'Залп',
    torpedo: 'Торпеда',
    cancel: 'Отмена',
    row: 'Строка',
    column: 'Колонка',
    menu: 'Меню',
    leave_battle: 'Покинуть бой?',
    leave_battle_text: 'Текущий бой будет завершён без награды.',
    stay: 'Остаться',
    to_menu: 'В меню',
    main_menu: 'Главное меню',
    victory: 'Победа!',
    defeat: 'Поражение',
    captain_chest_opened: 'Сундук капитана открыт',
    crew_saved_loot: 'Команда спасла часть добычи',
    to_campaign: 'В кампанию',
    play_again: 'Играть снова',
    try_again: 'Попробовать снова',
    double_reward: 'Удвоить за рекламу',
    double_reward_full: 'Удвоить награду за рекламу',
    double_reward_ad: 'Удвоить награду за рекламу',
    reward_received: 'Награда получена',
    reward_doubled: 'Награда удвоена',
    test_ad_watched: 'Тестовая реклама просмотрена',
    gold_reward: 'Получено золота',
    xp_reward: 'Получено опыта',
    career_progress: 'Прогресс карьеры',
    rank_progress: 'Прогресс ранга',
    career_xp: 'Опыт карьеры',
    rank_up_title: 'Поздравляем!',
    rank_up_text: 'Вам присвоен новый ранг:',
    rank_reward: 'Премия за ранг',
    continue: 'Продолжить',
    shop_title: 'Пиратская лавка',
    shop_tab_abilities: 'Способности',
    shop_tab_upgrades: 'Улучшения',
    buy: 'Купить',
    selected: 'Выбрано',
    select: 'Выбрать',
    not_enough_gold: 'Не хватает золота',
    max_level: 'Максимальный уровень',
    max_level_short: 'Макс.',
    upgrade_level: 'Уровень: {level}/5',
    no_charges: 'Нет зарядов',
    rare_chest: 'Редкий сундук',
    rare_chest_open: 'Открыть редкий сундук',
    rare_chest_later: 'Редкий сундук будет доступен позже',
    daily_chest_cooldown: 'Следующий сундук через {time}',
    ad_placeholder: 'Реклама будет подключена позже',
    coming_soon: 'Скоро',
    skin_selected: 'Скин выбран',
    purchase_ready: 'Покупка готова',
    hit: 'Попадание!',
    miss: 'Промах!',
    opponent_hit: 'Соперник попал!',
    opponent_miss: 'Соперник промахнулся.',
    victory_log: 'Победа! Сундук ждёт капитана.',
    defeat_log: 'Флот разбит. Команда отступает.',
    daily_already_opened: 'Сундук уже открыт. Новый будет завтра.'
    ,
    in_stock: 'В наличии: {count}',
    locked_island: 'Этот остров пока закрыт',
    island_status: 'Остров {id}: {name}',
    captain_level: 'Капитан ур. {level}',
    quick_location_1: 'Открытое море',
    quick_location_2: 'Штормовая линия',
    quick_location_3: 'Торговый фарватер',
    quick_location_4: 'Безымянная отмель',
    radar_hint: '{ability}: выберите центр области 3x3.',
    barrage_hint: '{ability}: выберите центр креста.',
    torpedo_hint: '{ability}: выберите строку или колонку и клетку.',
    radar_found: 'Радар поймал корабельный сигнал!',
    radar_empty: 'Радар показывает пустую воду.',
    barrage_empty: 'Все клетки залпа уже разведаны.',
    torpedo_empty: 'Эта линия уже прострелена.',
    cell_already: 'Эта клетка уже разведана.',
    enemy_ship_sunk: 'Корабль врага потоплен!',
    opponent_aiming: 'Соперник целится...',
    opponent_ship_sunk: 'Соперник потопил ваш корабль!',
    daily_xp_bonus: ' и +{amount} XP',
    level_1: 'Учебная бухта',
    level_2: 'Пиратский залив',
    level_3: 'Остров рифов',
    level_4: 'Туманный пролив',
    level_5: 'Форт корсаров',
    level_6: 'Ледяные воды',
    level_7: 'Вулканический архипелаг',
    level_8: 'Залив кракена',
    level_9: 'Проклятая гавань',
    level_10: 'Флагман Черной Бороды',
    shop_radarCharge_name: '+1 заряд радара',
    shop_radarCharge_desc: 'Дополнительный скан 3x3 в следующем бою.',
    shop_barrageCharge_name: '+1 заряд залпа',
    shop_barrageCharge_desc: 'Один дополнительный выстрел крестом.',
    shop_torpedoCharge_name: '+1 заряд торпеды',
    shop_torpedoCharge_desc: 'Дополнительная атака по строке или колонке.',
    shop_scoutPack_name: 'Набор разведчика',
    shop_scoutPack_desc: '+2 заряда радара.',
    shop_artilleryPack_name: 'Набор артиллериста',
    shop_artilleryPack_desc: '+2 заряда залпа.',
    shop_assaultPack_name: 'Набор штурмовика',
    shop_assaultPack_desc: '+2 заряда торпеды.',
    shop_battlePack_name: 'Боевой набор',
    shop_battlePack_desc: '+1 радар, +1 залп и +1 торпеда.',
    shop_salvoCharge_name: '+1 заряд залпа',
    shop_salvoCharge_desc: 'Один дополнительный выстрел крестом.',
    shop_radarLevel_name: 'Улучшение радара I–V',
    shop_radarLevel_desc: 'Каждый уровень даёт +1 заряд радара в бою.',
    shop_salvoLevel_name: 'Улучшение залпа I–V',
    shop_salvoLevel_desc: 'Каждый уровень даёт +1 заряд залпа в бою.',
    shop_torpedoLevel_name: 'Улучшение торпеды I–V',
    shop_torpedoLevel_desc: 'Каждый уровень даёт +1 заряд торпеды в бою.',
    shop_goldBonusLevel_name: 'Бонус золота I–V',
    shop_goldBonusLevel_desc: '+5% золота за каждый уровень улучшения.',
    shop_xpBonusLevel_name: 'Бонус опыта I–V',
    shop_xpBonusLevel_desc: '+5% опыта за каждый уровень улучшения.',
    shop_shopDiscount_name: 'Скидка магазина I–V',
    shop_shopDiscount_desc: 'Будущая скидка на покупки.',
    shop_startingBonus_name: 'Стартовый бонус I–V',
    shop_startingBonus_desc: 'Будущий бонус перед боем.',
    shop_shipSkinGoldCorsair_name: 'Скин корабля “Золотой корсар”',
    shop_shipSkinGoldCorsair_desc: 'Золотые флаги и теплый оттенок кораблей.',
    shop_waterSkinTropical_name: 'Скин воды “Тропическое море”',
    shop_waterSkinTropical_desc: 'Более яркий тропический оттенок моря.'
  },
  en: {
    menu_title: 'Pirate\nSea Battle',
    menu_title_line_1: 'Pirate Sea Battle',
    menu_title_line_2: 'Treasure Map',
    menu_subtitle: 'TREASURE CAMPAIGN',
    play: 'Play',
    campaign: 'Campaign',
    campaign_stars: 'Campaign Stars',
    next_reward: 'Next Reward',
    quick_battle: 'Quick Battle',
    arsenal: 'Arsenal',
    settings: 'Settings',
    close: 'Close',
    back: 'Back',
    shop: 'Shop',
    career: 'CAREER',
    rank: 'Rank',
    gold: 'Gold',
    price_gold: '{amount} gold',
    xp: 'XP',
    admiral_chest: 'Admiral Chest',
    open_for_ad: 'Open with ad',
    available_tomorrow: 'Available tomorrow',
    available: 'Available',
    opens_in: 'In {time}',
    wins_until_open: 'Wins left: {count}',
    daily_chest_rules: 'Once every 24 hours: gold, XP, chance for an ability.',
    rare_chest_rules: 'Every 6 hours or after 3 wins: more gold, XP and abilities.',
    chapter: 'Chapter',
    locked_chapter: 'Chapter locked',
    opens_after_previous_chapter: 'Opens after completing the previous chapter',
    open: 'Open',
    tomorrow: 'Tomorrow',
    language: 'Language',
    sfx: 'Effects sound',
    music: 'Music',
    music_volume: 'Music volume',
    sfx_volume: 'Effects volume',
    on: 'On',
    off: 'Off',
    fleet_preparation: 'Fleet Preparation',
    preparation_timer: 'Preparation',
    ships: 'SHIPS',
    ships_hint: 'Choose a ship and place it on the grid.',
    commands: 'COMMANDS',
    rotate_horizontal: 'Rotate: horizontal',
    rotate_vertical: 'Rotate: vertical',
    auto_place: 'Auto Place',
    current_ship: 'Current Ship',
    orientation_horizontal: 'Horizontal',
    orientation_vertical: 'Vertical',
    ship_deck: '{count}-deck ship',
    ready_to_battle: 'Ready',
    cannot_place: 'Cannot place here',
    fleet_ready: 'Fleet is ready',
    your_fleet: 'Your Fleet',
    enemy_waters: 'Opponent Waters',
    logbook: 'Logbook',
    your_turn: 'Your turn',
    opponent_turn: 'Opponent turn',
    radar: 'Radar',
    barrage: 'Barrage',
    salvo: 'Salvo',
    torpedo: 'Torpedo',
    cancel: 'Cancel',
    row: 'Row',
    column: 'Column',
    menu: 'Menu',
    leave_battle: 'Leave battle?',
    leave_battle_text: 'This battle will end without rewards.',
    stay: 'Stay',
    to_menu: 'To menu',
    main_menu: 'Main Menu',
    victory: 'Victory!',
    defeat: 'Defeat',
    captain_chest_opened: 'Captain chest opened',
    crew_saved_loot: 'The crew saved part of the loot',
    to_campaign: 'To Campaign',
    play_again: 'Play again',
    try_again: 'Try again',
    double_reward: 'Double with ad',
    double_reward_full: 'Double reward with ad',
    double_reward_ad: 'Double reward with ad',
    reward_received: 'Reward claimed',
    reward_doubled: 'Reward doubled',
    test_ad_watched: 'Test ad watched',
    gold_reward: 'Gold earned',
    xp_reward: 'XP earned',
    career_progress: 'Career progress',
    rank_progress: 'Rank progress',
    career_xp: 'Career XP',
    rank_up_title: 'Congratulations!',
    rank_up_text: 'You have been promoted to:',
    rank_reward: 'Rank bonus',
    continue: 'Continue',
    shop_title: 'Pirate Shop',
    shop_tab_abilities: 'Abilities',
    shop_tab_upgrades: 'Upgrades',
    buy: 'Buy',
    selected: 'Selected',
    select: 'Select',
    not_enough_gold: 'Not enough gold',
    max_level: 'Maximum level',
    max_level_short: 'Max',
    upgrade_level: 'Level: {level}/5',
    no_charges: 'No charges',
    rare_chest: 'Rare Chest',
    rare_chest_open: 'Open rare chest',
    rare_chest_later: 'Rare chest will be available later',
    daily_chest_cooldown: 'Next chest in {time}',
    ad_placeholder: 'Ads will be connected later',
    coming_soon: 'Coming soon',
    skin_selected: 'Skin selected',
    purchase_ready: 'Purchase ready',
    hit: 'Hit!',
    miss: 'Miss!',
    opponent_hit: 'Opponent hit!',
    opponent_miss: 'Opponent missed.',
    victory_log: 'Victory! The chest awaits.',
    defeat_log: 'Fleet defeated. The crew retreats.',
    daily_already_opened: 'Chest already opened. Come back tomorrow.',
    in_stock: 'Available: {count}',
    locked_island: 'This operation is locked',
    island_status: 'Operation {id}: {name}',
    captain_level: 'Captain lvl. {level}',
    quick_location_1: 'Open Sea',
    quick_location_2: 'Storm Line',
    quick_location_3: 'Trade Route',
    quick_location_4: 'Nameless Shoal',
    radar_hint: '{ability}: choose the center of a 3x3 area.',
    barrage_hint: '{ability}: choose the center of the cross.',
    torpedo_hint: '{ability}: choose a row or column cell.',
    radar_found: 'Radar caught a ship signal!',
    radar_empty: 'Radar shows empty water.',
    barrage_empty: 'All barrage cells are already scouted.',
    torpedo_empty: 'This line has already been fired through.',
    cell_already: 'This cell is already scouted.',
    enemy_ship_sunk: 'Enemy ship sunk!',
    opponent_aiming: 'Opponent is aiming...',
    opponent_ship_sunk: 'Opponent sunk your ship!',
    daily_xp_bonus: ' and +{amount} XP',
    level_1: 'Training Bay',
    level_2: 'Pirate Gulf',
    level_3: 'Reef Island',
    level_4: 'Misty Strait',
    level_5: 'Corsair Fort',
    level_6: 'Icy Waters',
    level_7: 'Volcanic Archipelago',
    level_8: 'Kraken Bay',
    level_9: 'Cursed Harbor',
    level_10: "Blackbeard's Flagship",
    shop_radarCharge_name: '+1 radar charge',
    shop_radarCharge_desc: 'An extra 3x3 scan in the next battle.',
    shop_barrageCharge_name: '+1 barrage charge',
    shop_barrageCharge_desc: 'One extra cross-shaped strike.',
    shop_torpedoCharge_name: '+1 torpedo charge',
    shop_torpedoCharge_desc: 'An extra row or column attack.',
    shop_scoutPack_name: 'Scout Pack',
    shop_scoutPack_desc: '+2 radar charges.',
    shop_artilleryPack_name: 'Artillery Pack',
    shop_artilleryPack_desc: '+2 salvo charges.',
    shop_assaultPack_name: 'Assault Pack',
    shop_assaultPack_desc: '+2 torpedo charges.',
    shop_battlePack_name: 'Battle Pack',
    shop_battlePack_desc: '+1 radar, +1 salvo and +1 torpedo.',
    shop_salvoCharge_name: '+1 salvo charge',
    shop_salvoCharge_desc: 'One extra cross-shaped strike.',
    shop_radarLevel_name: 'Radar Upgrade I–V',
    shop_radarLevel_desc: 'Each level grants +1 radar charge in battle.',
    shop_salvoLevel_name: 'Salvo Upgrade I–V',
    shop_salvoLevel_desc: 'Each level grants +1 salvo charge in battle.',
    shop_torpedoLevel_name: 'Torpedo Upgrade I–V',
    shop_torpedoLevel_desc: 'Each level grants +1 torpedo charge in battle.',
    shop_goldBonusLevel_name: 'Gold Bonus I–V',
    shop_goldBonusLevel_desc: '+5% gold per upgrade level.',
    shop_xpBonusLevel_name: 'XP Bonus I–V',
    shop_xpBonusLevel_desc: '+5% XP per upgrade level.',
    shop_shopDiscount_name: 'Shop Discount I–V',
    shop_shopDiscount_desc: 'Future discount for purchases.',
    shop_startingBonus_name: 'Starting Bonus I–V',
    shop_startingBonus_desc: 'Future pre-battle bonus.',
    shop_shipSkinGoldCorsair_name: 'Ship skin “Golden Corsair”',
    shop_shipSkinGoldCorsair_desc: 'Golden flags and a warm ship tint.',
    shop_waterSkinTropical_name: 'Water skin “Tropical Sea”',
    shop_waterSkinTropical_desc: 'A brighter tropical sea tint.'
  },
  tr: {
    menu_title: 'Korsan\nDeniz Savaşı',
    menu_title_line_1: 'Korsan Deniz Savaşı',
    menu_title_line_2: 'Hazine Haritası',
    menu_subtitle: 'HAZİNE SEFERİ',
    play: 'Oyna',
    campaign: 'Sefer',
    campaign_stars: 'Sefer Yıldızları',
    next_reward: 'Sonraki Ödül',
    quick_battle: 'Hızlı Savaş',
    arsenal: 'Cephanelik',
    settings: 'Ayarlar',
    close: 'Kapat',
    back: 'Geri',
    shop: 'Dükkan',
    career: 'KARİYER',
    rank: 'Rütbe',
    gold: 'Altın',
    price_gold: '{amount} altın',
    xp: 'XP',
    admiral_chest: 'Amiral Sandığı',
    open_for_ad: 'Reklamla aç',
    available_tomorrow: 'Yarın açılır',
    available: 'Açık',
    opens_in: '{time} sonra',
    wins_until_open: 'Kalan zafer: {count}',
    daily_chest_rules: '24 saatte bir: altın, XP, yetenek şansı.',
    rare_chest_rules: '6 saatte bir veya 3 zaferden sonra: daha çok altın, XP ve yetenek.',
    chapter: 'Bölüm',
    locked_chapter: 'Bölüm kilitli',
    opens_after_previous_chapter: 'Önceki bölüm tamamlanınca açılır',
    open: 'Aç',
    tomorrow: 'Yarın',
    language: 'Dil',
    sfx: 'Efekt sesi',
    music: 'Müzik',
    music_volume: 'Müzik sesi',
    sfx_volume: 'Efekt sesi',
    on: 'Açık',
    off: 'Kapalı',
    fleet_preparation: 'Filo Hazırlığı',
    preparation_timer: 'Hazırlık',
    ships: 'GEMİLER',
    ships_hint: 'Bir gemi seç ve tabloya yerleştir.',
    commands: 'KOMUTLAR',
    rotate_horizontal: 'Çevir: yatay',
    rotate_vertical: 'Çevir: dikey',
    auto_place: 'Otomatik Yerleştir',
    current_ship: 'Geçerli Gemi',
    orientation_horizontal: 'Yatay',
    orientation_vertical: 'Dikey',
    ship_deck: '{count} güverteli gemi',
    ready_to_battle: 'Savaşa Hazır',
    cannot_place: 'Buraya yerleştirilemez',
    fleet_ready: 'Filo hazır',
    your_fleet: 'Filon',
    enemy_waters: 'Rakip Suları',
    logbook: 'Seyir Defteri',
    your_turn: 'Sıra sende',
    opponent_turn: 'Rakibin sırası',
    radar: 'Radar',
    barrage: 'Yaylım',
    salvo: 'Yaylım',
    torpedo: 'Torpido',
    cancel: 'İptal',
    row: 'Satır',
    column: 'Sütun',
    menu: 'Menü',
    leave_battle: 'Savaştan çıkılsın mı?',
    leave_battle_text: 'Bu savaş ödülsüz bitecek.',
    stay: 'Kal',
    to_menu: 'Menüye',
    main_menu: 'Ana Menü',
    victory: 'Zafer!',
    defeat: 'Yenilgi',
    captain_chest_opened: 'Kaptan sandığı açıldı',
    crew_saved_loot: 'Mürettebat ganimetin bir kısmını kurtardı',
    to_campaign: 'Sefere',
    play_again: 'Tekrar oyna',
    try_again: 'Tekrar dene',
    double_reward: 'Reklamla ikiye katla',
    double_reward_full: 'Ödülü reklamla ikiye katla',
    double_reward_ad: 'Ödülü reklamla ikiye katla',
    reward_received: 'Ödül alındı',
    reward_doubled: 'Ödül ikiye katlandı',
    test_ad_watched: 'Test reklamı izlendi',
    gold_reward: 'Kazanılan altın',
    xp_reward: 'Kazanılan XP',
    career_progress: 'Kariyer ilerlemesi',
    rank_progress: 'Rütbe ilerlemesi',
    career_xp: 'Kariyer XP',
    rank_up_title: 'Tebrikler!',
    rank_up_text: 'Yeni rütben:',
    rank_reward: 'Rütbe ödülü',
    continue: 'Devam',
    shop_title: 'Korsan Dükkanı',
    shop_tab_abilities: 'Yetenekler',
    shop_tab_upgrades: 'Geliştirmeler',
    buy: 'Satın al',
    selected: 'Seçildi',
    select: 'Seç',
    not_enough_gold: 'Altın yetersiz',
    max_level: 'Maksimum seviye',
    max_level_short: 'Maks.',
    upgrade_level: 'Seviye: {level}/5',
    no_charges: 'Hak yok',
    rare_chest: 'Nadir Sandık',
    rare_chest_open: 'Nadir sandığı aç',
    rare_chest_later: 'Nadir sandık daha sonra açılacak',
    daily_chest_cooldown: 'Sonraki sandık: {time}',
    ad_placeholder: 'Reklam daha sonra bağlanacak',
    coming_soon: 'Yakında',
    skin_selected: 'Görünüm seçildi',
    purchase_ready: 'Satın alma tamam',
    hit: 'İsabet!',
    miss: 'Iska!',
    opponent_hit: 'Rakip vurdu!',
    opponent_miss: 'Rakip ıskaladı.',
    victory_log: 'Zafer! Sandık seni bekliyor.',
    defeat_log: 'Filo yenildi. Mürettebat çekiliyor.',
    daily_already_opened: 'Sandık açıldı. Yarın tekrar gel.',
    in_stock: 'Mevcut: {count}',
    locked_island: 'Bu görev kilitli',
    island_status: 'Görev {id}: {name}',
    captain_level: 'Kaptan sv. {level}',
    quick_location_1: 'Açık Deniz',
    quick_location_2: 'Fırtına Hattı',
    quick_location_3: 'Ticaret Rotası',
    quick_location_4: 'Adsız Sığlık',
    radar_hint: '{ability}: 3x3 alanın merkezini seç.',
    barrage_hint: '{ability}: haç saldırısının merkezini seç.',
    torpedo_hint: '{ability}: satır ya da sütun hücresi seç.',
    radar_found: 'Radar gemi sinyali yakaladı!',
    radar_empty: 'Radar boş su gösteriyor.',
    barrage_empty: 'Tüm yaylım hücreleri keşfedildi.',
    torpedo_empty: 'Bu hat zaten ateşlendi.',
    cell_already: 'Bu hücre zaten keşfedildi.',
    enemy_ship_sunk: 'Rakip gemi battı!',
    opponent_aiming: 'Rakip nişan alıyor...',
    opponent_ship_sunk: 'Rakip gemini batırdı!',
    daily_xp_bonus: ' ve +{amount} XP',
    level_1: 'Eğitim Koyu',
    level_2: 'Korsan Körfezi',
    level_3: 'Resif Adası',
    level_4: 'Sisli Boğaz',
    level_5: 'Korsan Hisarı',
    level_6: 'Buzlu Sular',
    level_7: 'Volkanik Takımada',
    level_8: 'Kraken Körfezi',
    level_9: 'Lanetli Liman',
    level_10: 'Karasakalın Amiral Gemisi',
    shop_radarCharge_name: '+1 radar hakkı',
    shop_radarCharge_desc: 'Sonraki savaşta ekstra 3x3 tarama.',
    shop_barrageCharge_name: '+1 yaylım hakkı',
    shop_barrageCharge_desc: 'Ekstra haç şeklinde saldırı.',
    shop_torpedoCharge_name: '+1 torpido hakkı',
    shop_torpedoCharge_desc: 'Ekstra satır veya sütun saldırısı.',
    shop_scoutPack_name: 'Keşif Paketi',
    shop_scoutPack_desc: '+2 radar hakkı.',
    shop_artilleryPack_name: 'Topçu Paketi',
    shop_artilleryPack_desc: '+2 yaylım hakkı.',
    shop_assaultPack_name: 'Saldırı Paketi',
    shop_assaultPack_desc: '+2 torpido hakkı.',
    shop_battlePack_name: 'Savaş Paketi',
    shop_battlePack_desc: '+1 radar, +1 yaylım ve +1 torpido.',
    shop_salvoCharge_name: '+1 yaylım hakkı',
    shop_salvoCharge_desc: 'Ekstra haç şeklinde saldırı.',
    shop_radarLevel_name: 'Radar Geliştirme I–V',
    shop_radarLevel_desc: 'Her seviye savaşta +1 radar hakkı verir.',
    shop_salvoLevel_name: 'Yaylım Geliştirme I–V',
    shop_salvoLevel_desc: 'Her seviye savaşta +1 yaylım hakkı verir.',
    shop_torpedoLevel_name: 'Torpido Geliştirme I–V',
    shop_torpedoLevel_desc: 'Her seviye savaşta +1 torpido hakkı verir.',
    shop_goldBonusLevel_name: 'Altın Bonusu I–V',
    shop_goldBonusLevel_desc: 'Her geliştirme seviyesi +%5 altın verir.',
    shop_xpBonusLevel_name: 'XP Bonusu I–V',
    shop_xpBonusLevel_desc: 'Her geliştirme seviyesi +%5 XP verir.',
    shop_shopDiscount_name: 'Dükkan İndirimi I–V',
    shop_shopDiscount_desc: 'Gelecekte satın alma indirimi.',
    shop_startingBonus_name: 'Başlangıç Bonusu I–V',
    shop_startingBonus_desc: 'Gelecekte savaş öncesi bonus.',
    shop_shipSkinGoldCorsair_name: 'Gemi görünümü “Altın Korsan”',
    shop_shipSkinGoldCorsair_desc: 'Altın bayraklar ve sıcak gemi tonu.',
    shop_waterSkinTropical_name: 'Su görünümü “Tropik Deniz”',
    shop_waterSkinTropical_desc: 'Daha parlak tropik deniz tonu.'
  }
};

let currentLanguage = 'ru';

export const LocalizationService = {
  init(profile) {
    currentLanguage = profile?.settings?.language ?? currentLanguage;
    return currentLanguage;
  },

  t(key, params = {}) {
    const value = translations[currentLanguage]?.[key] ?? translations.ru[key] ?? key;
    return Object.entries(params).reduce((text, [param, replacement]) => {
      return text.replaceAll(`{${param}}`, String(replacement));
    }, value);
  },

  setLanguage(lang) {
    currentLanguage = translations[lang] ? lang : 'ru';
    return currentLanguage;
  },

  getLanguage() {
    return currentLanguage;
  },

  getSupportedLanguages() {
    return SUPPORTED_LANGUAGES;
  }
};

export const t = (key, params) => LocalizationService.t(key, params);
